import { Router } from "express";
import { randomBytes } from "node:crypto";
import { z } from "zod";
import { supabaseAdmin } from "../lib/supabase.js";
import { requireAuth } from "../middleware/auth.js";
import { getIO, emitMembershipUpdate, emitRoleChangeEvent, emitPinUpdateEvent, emitNewPostEvent } from "../socket.js";
import { isBackendAdmin } from "../lib/admin.js";

export const operationsRouter = Router();
const rp = (res: any, fn: () => Promise<any>) => fn().then((value) => res.json(value)).catch((err: any) => res.status(err?.name === "ZodError" ? 400 : 500).json({ error: err?.message || "Internal server error" }));
const str = z.string().min(1).max(255);
const id = z.string().uuid();
const body = (shape: Record<string, z.ZodTypeAny>): z.ZodType<any> => z.object({ clerkUserId: str, ...shape });
const now = () => new Date().toISOString();
const token = () => randomBytes(24).toString("base64url");

async function group(groupId: string) { const { data } = await supabaseAdmin.from("conversations").select("*").eq("id", groupId).eq("type", "group").maybeSingle(); if (!data) throw new Error("Group not found"); return data; }
async function channel(channelId: string) { const { data } = await supabaseAdmin.from("channels").select("*").eq("id", channelId).maybeSingle(); if (!data) throw new Error("Channel not found"); return data; }
async function gm(user: string, conversationId: string) { const { data } = await supabaseAdmin.from("conversation_members").select("*").eq("conversation_id", conversationId).eq("clerk_user_id", user).maybeSingle(); if (!data) throw new Error("You are not a member of this group"); return data; }
async function cm(user: string, channelId: string) { const { data } = await supabaseAdmin.from("channel_members").select("*").eq("channel_id", channelId).eq("clerk_user_id", user).maybeSingle(); if (!data) throw new Error("You are not a member of this channel"); return data; }
async function ga(user: string, conversationId: string) { if (isBackendAdmin(user)) return { role: "admin", backendAdmin: true }; const m = await gm(user, conversationId); if (m.role !== "admin") throw new Error("Only group admins can perform this action"); return m; }
async function ca(user: string, channelId: string) { if (isBackendAdmin(user)) return { role: "admin", backendAdmin: true }; const m = await cm(user, channelId); if (m.role !== "admin") throw new Error("Only channel admins can perform this action"); return m; }
async function audit(targetType: "group" | "channel", targetId: string, actor: string, action: string, target?: string, metadata: Record<string, unknown> = {}) { await supabaseAdmin.from("admin_audit_log").insert({ target_type: targetType, target_id: targetId, actor_clerk_user_id: actor, action, target_clerk_user_id: target || null, metadata }); }
function route(path: string, handler: (data: any) => Promise<any>) { operationsRouter.post(`/${path}`, requireAuth, (req, res) => rp(res, async () => handler(req.body))); }
function emit(event: string, payload: any) { const io = getIO(); if (io) io.emit(event as any, payload); }

route("createGroup", async (d) => { const x = body({ name: z.string().min(1).max(100), description: z.string().max(500).optional(), memberClerkIds: z.array(str).max(1000).default([]) }).parse(d); const { data, error } = await supabaseAdmin.from("conversations").insert({ type: "group", name: x.name, description: x.description || null, created_by: x.clerkUserId }).select().single(); if (error) throw new Error(error.message); const members = [...new Set([x.clerkUserId, ...x.memberClerkIds])].map((u) => ({ conversation_id: data.id, clerk_user_id: u, role: u === x.clerkUserId ? "admin" : "member" })); const { error: me } = await supabaseAdmin.from("conversation_members").insert(members); if (me) throw new Error(me.message); return data; });
route("renameGroup", async (d) => { const x = body({ groupId: id, name: z.string().min(1).max(100) }).parse(d); await ga(x.clerkUserId, x.groupId); const { data, error } = await supabaseAdmin.from("conversations").update({ name: x.name, updated_at: now() }).eq("id", x.groupId).select().single(); if (error) throw new Error(error.message); return data; });
route("updateGroupDescription", async (d) => { const x = body({ groupId: id, description: z.string().max(500).nullable() }).parse(d); await ga(x.clerkUserId, x.groupId); const { data, error } = await supabaseAdmin.from("conversations").update({ description: x.description, updated_at: now() }).eq("id", x.groupId).select().single(); if (error) throw new Error(error.message); return data; });
route("deleteGroup", async (d) => { const x = body({ groupId: id }).parse(d); await ga(x.clerkUserId, x.groupId); const { error } = await supabaseAdmin.from("conversations").update({ deleted_at: now(), updated_at: now() }).eq("id", x.groupId); if (error) throw new Error(error.message); return { success: true }; });
route("addMember", async (d) => { const x = body({ groupId: id, memberClerkId: str }).parse(d); await ga(x.clerkUserId, x.groupId); const { error } = await supabaseAdmin.from("conversation_members").upsert({ conversation_id: x.groupId, clerk_user_id: x.memberClerkId, role: "member" }, { onConflict: "conversation_id,clerk_user_id" }); if (error) throw new Error(error.message); await audit("group", x.groupId, x.clerkUserId, "member.added", x.memberClerkId); emitMembershipUpdate(x.groupId, { action: "added", clerkUserId: x.memberClerkId }); return { success: true }; });
route("removeMember", async (d) => { const x = body({ groupId: id, memberClerkId: str }).parse(d); await ga(x.clerkUserId, x.groupId); if (x.memberClerkId === x.clerkUserId) throw new Error("Use leaveGroup to remove yourself"); const { error } = await supabaseAdmin.from("conversation_members").delete().eq("conversation_id", x.groupId).eq("clerk_user_id", x.memberClerkId); if (error) throw new Error(error.message); await audit("group", x.groupId, x.clerkUserId, "member.removed", x.memberClerkId); emitMembershipUpdate(x.groupId, { action: "removed", clerkUserId: x.memberClerkId }); return { success: true }; });
route("leaveGroup", async (d) => { const x = body({ groupId: id }).parse(d); await gm(x.clerkUserId, x.groupId); const { error } = await supabaseAdmin.from("conversation_members").delete().eq("conversation_id", x.groupId).eq("clerk_user_id", x.clerkUserId); if (error) throw new Error(error.message); emitMembershipUpdate(x.groupId, { action: "left", clerkUserId: x.clerkUserId }); return { success: true }; });
route("setMemberRole", async (d) => { const x = body({ groupId: id, memberClerkId: str, role: z.enum(["admin", "member"]) }).parse(d); await ga(x.clerkUserId, x.groupId); if (x.role === "member") { const { count } = await supabaseAdmin.from("conversation_members").select("id", { count: "exact", head: true }).eq("conversation_id", x.groupId).eq("role", "admin"); if ((count || 0) <= 1 && x.memberClerkId === x.clerkUserId) throw new Error("Cannot remove the last admin"); } const { error } = await supabaseAdmin.from("conversation_members").update({ role: x.role }).eq("conversation_id", x.groupId).eq("clerk_user_id", x.memberClerkId); if (error) throw new Error(error.message); await audit("group", x.groupId, x.clerkUserId, "member.role_changed", x.memberClerkId, { role: x.role }); emitRoleChangeEvent(x.groupId, { clerkUserId: x.memberClerkId, role: x.role }); return { success: true }; });
route("muteMember", async (d) => memberMute(d, true));
route("unmuteMember", async (d) => memberMute(d, false));
async function memberMute(d: any, muted: boolean) { const x = body({ groupId: id, memberClerkId: str, seconds: z.number().int().min(0).max(31536000).optional() }).parse(d); await ga(x.clerkUserId, x.groupId); const until = muted ? new Date(Date.now() + (x.seconds || 31536000) * 1000).toISOString() : null; const { error } = await supabaseAdmin.from("conversation_members").update({ muted_until: until }).eq("conversation_id", x.groupId).eq("clerk_user_id", x.memberClerkId); if (error) throw new Error(error.message); await audit("group", x.groupId, x.clerkUserId, muted ? "member.muted" : "member.unmuted", x.memberClerkId); return { success: true, muted, mutedUntil: until }; }
route("kickMember", async (d) => { const x = body({ groupId: id, memberClerkId: str }).parse(d); await ga(x.clerkUserId, x.groupId); const { error } = await supabaseAdmin.from("conversation_members").delete().eq("conversation_id", x.groupId).eq("clerk_user_id", x.memberClerkId); if (error) throw new Error(error.message); await audit("group", x.groupId, x.clerkUserId, "member.kicked", x.memberClerkId); return { success: true }; });
route("banMember", async (d) => { const x = body({ groupId: id, memberClerkId: str, reason: z.string().max(500).optional() }).parse(d); await ga(x.clerkUserId, x.groupId); await supabaseAdmin.from("conversation_members").delete().eq("conversation_id", x.groupId).eq("clerk_user_id", x.memberClerkId); await audit("group", x.groupId, x.clerkUserId, "member.banned", x.memberClerkId, { reason: x.reason || null }); return { success: true }; });
route("unbanMember", async (d) => { const x = body({ groupId: id, memberClerkId: str }).parse(d); await ga(x.clerkUserId, x.groupId); await audit("group", x.groupId, x.clerkUserId, "member.unbanned", x.memberClerkId); return { success: true }; });
route("setMemberRestrictions", async (d) => { const x = body({ groupId: id, memberClerkId: str, restrictions: z.record(z.boolean()) }).parse(d); await ga(x.clerkUserId, x.groupId); const { error } = await supabaseAdmin.from("conversation_members").update({ restrictions: x.restrictions }).eq("conversation_id", x.groupId).eq("clerk_user_id", x.memberClerkId); if (error) throw new Error(error.message); return { success: true }; });
route("setSlowMode", async (d) => { const x = body({ groupId: id, seconds: z.number().int().min(0).max(86400) }).parse(d); await ga(x.clerkUserId, x.groupId); const { error } = await supabaseAdmin.from("conversations").update({ slow_mode_seconds: x.seconds }).eq("id", x.groupId); if (error) throw new Error(error.message); return { success: true, seconds: x.seconds }; });
route("getGroupMembers", async (d) => { const x = body({ groupId: id }).parse(d); await gm(x.clerkUserId, x.groupId); const { data, error } = await supabaseAdmin.from("conversation_members").select("*").eq("conversation_id", x.groupId).order("joined_at"); if (error) throw new Error(error.message); return data || []; });
route("getGroupById", async (d) => { const x = body({ groupId: id }).parse(d); await gm(x.clerkUserId, x.groupId); const g = await group(x.groupId); const { data: members } = await supabaseAdmin.from("conversation_members").select("*").eq("conversation_id", x.groupId); return { ...g, members: members || [] }; });
route("listUserGroups", async (d) => { const x = body({}).parse(d); const { data: ms } = await supabaseAdmin.from("conversation_members").select("conversation_id, role").eq("clerk_user_id", x.clerkUserId); const ids = (ms || []).map((m: any) => m.conversation_id); if (!ids.length) return []; const { data } = await supabaseAdmin.from("conversations").select("*").in("id", ids).eq("type", "group").is("deleted_at", null); return (data || []).map((g: any) => ({ ...g, membership: ms?.find((m: any) => m.conversation_id === g.id) })); });

route("createChannel", async (d) => { const x = body({ name: z.string().min(1).max(80), description: z.string().max(2048).optional(), isPrivate: z.boolean().default(false), isBroadcast: z.boolean().default(true) }).parse(d); const { data: conv, error: ce } = await supabaseAdmin.from("conversations").insert({ type: "channel", name: x.name, description: x.description || null, created_by: x.clerkUserId }).select().single(); if (ce) throw new Error(ce.message); const { data, error } = await supabaseAdmin.from("channels").insert({ conversation_id: conv.id, name: x.name, public_slug: `${x.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${randomBytes(3).toString("hex")}`, description: x.description || null, is_private: x.isPrivate, is_broadcast: x.isBroadcast, created_by: x.clerkUserId }).select().single(); if (error) throw new Error(error.message); await supabaseAdmin.from("channel_members").insert({ channel_id: data.id, clerk_user_id: x.clerkUserId, role: "admin" }); await supabaseAdmin.from("conversation_members").insert({ conversation_id: conv.id, clerk_user_id: x.clerkUserId, role: "admin" }); return { ...data, conversation: conv }; });
route("renameChannel", async (d) => channelPatch(d, "name", "name"));
route("updateChannelDescription", async (d) => channelPatch(d, "description", "description"));
async function channelPatch(d: any, field: string, column: string) { const x = body({ channelId: id, value: z.string().max(2048) }).parse(d); await ca(x.clerkUserId, x.channelId); const patch: any = {}; patch[column] = x.value; const { data, error } = await supabaseAdmin.from("channels").update(patch).eq("id", x.channelId).select().single(); if (error) throw new Error(error.message); return data; }
route("deleteChannel", async (d) => { const x = body({ channelId: id }).parse(d); await ca(x.clerkUserId, x.channelId); const { error } = await supabaseAdmin.from("channels").update({ archived_at: now() }).eq("id", x.channelId); if (error) throw new Error(error.message); return { success: true }; });
route("setChannelVisibility", async (d) => { const x = body({ channelId: id, isPrivate: z.boolean(), isDiscoverable: z.boolean().optional() }).parse(d); await ca(x.clerkUserId, x.channelId); const patch: any = { is_private: x.isPrivate }; if (x.isDiscoverable !== undefined) patch.is_discoverable = x.isDiscoverable; const { data, error } = await supabaseAdmin.from("channels").update(patch).eq("id", x.channelId).select().single(); if (error) throw new Error(error.message); return data; });
route("subscribeToChannel", async (d) => { const x = body({ channelId: id }).parse(d); const c = await channel(x.channelId); if (c.is_private) throw new Error("Private channels require an invite or approval"); const { error } = await supabaseAdmin.from("channel_members").upsert({ channel_id: x.channelId, clerk_user_id: x.clerkUserId, role: "subscriber" }, { onConflict: "channel_id,clerk_user_id" }); if (error) throw new Error(error.message); return { success: true }; });
route("unsubscribeFromChannel", async (d) => { const x = body({ channelId: id }).parse(d); const { error } = await supabaseAdmin.from("channel_members").delete().eq("channel_id", x.channelId).eq("clerk_user_id", x.clerkUserId).neq("role", "admin"); if (error) throw new Error(error.message); return { success: true }; });
route("getChannelSubscribers", async (d) => { const x = body({ channelId: id }).parse(d); await ca(x.clerkUserId, x.channelId); const { data, error } = await supabaseAdmin.from("channel_members").select("*").eq("channel_id", x.channelId); if (error) throw new Error(error.message); return data || []; });
route("getChannelById", async (d) => { const x = body({ channelId: id }).parse(d); await cm(x.clerkUserId, x.channelId); return channel(x.channelId); });
route("listUserChannels", async (d) => { const x = body({}).parse(d); const { data: ms } = await supabaseAdmin.from("channel_members").select("channel_id, role, muted").eq("clerk_user_id", x.clerkUserId); const ids = (ms || []).map((m: any) => m.channel_id); if (!ids.length) return []; const { data } = await supabaseAdmin.from("channels").select("*").in("id", ids).is("archived_at", null); return (data || []).map((c: any) => ({ ...c, membership: ms?.find((m: any) => m.channel_id === c.id) })); });

route("postMessage", async (d) => post(d, false));
route("schedulePost", async (d) => post(d, true));
async function post(d: any, scheduled: boolean) { const x = body({ channelId: id, text: z.string().max(5000).optional(), scheduledAt: z.string().datetime().optional(), silent: z.boolean().default(false), anonymousAdmin: z.boolean().default(false) }).parse(d); const c = await channel(x.channelId); const m = await ca(x.clerkUserId, x.channelId); if (!x.text?.trim()) throw new Error("Post text is required"); const { data, error } = await supabaseAdmin.from("messages").insert({ conversation_id: c.conversation_id, sender_clerk_id: x.clerkUserId, text: x.text, scheduled_at: scheduled ? (x.scheduledAt || new Date(Date.now() + 60000).toISOString()) : null, published_at: scheduled ? null : now(), silent: x.silent, anonymous_admin: x.anonymousAdmin }).select().single(); if (error) throw new Error(error.message); if (!scheduled) emitNewPostEvent(x.channelId, data); return data; }
route("publishScheduledPost", async (d) => { const x = body({ channelId: id, messageId: id }).parse(d); await ca(x.clerkUserId, x.channelId); const c = await channel(x.channelId); const { data, error } = await supabaseAdmin.from("messages").update({ scheduled_at: null, published_at: now() }).eq("id", x.messageId).eq("conversation_id", c.conversation_id).select().single(); if (error) throw new Error(error.message); emitNewPostEvent(x.channelId, data); return data; });
route("cancelScheduledPost", async (d) => { const x = body({ channelId: id, messageId: id }).parse(d); await ca(x.clerkUserId, x.channelId); const c = await channel(x.channelId); const { error } = await supabaseAdmin.from("messages").delete().eq("id", x.messageId).eq("conversation_id", c.conversation_id).not("scheduled_at", "is", null); if (error) throw new Error(error.message); return { success: true }; });
route("editPost", async (d) => { const x = body({ channelId: id, messageId: id, text: z.string().max(5000) }).parse(d); const c = await channel(x.channelId); await ca(x.clerkUserId, x.channelId); const { data, error } = await supabaseAdmin.from("messages").update({ text: x.text, edited_at: now() }).eq("id", x.messageId).eq("conversation_id", c.conversation_id).select().single(); if (error) throw new Error(error.message); return data; });
route("deletePost", async (d) => { const x = body({ channelId: id, messageId: id }).parse(d); const c = await channel(x.channelId); await ca(x.clerkUserId, x.channelId); const { error } = await supabaseAdmin.from("messages").delete().eq("id", x.messageId).eq("conversation_id", c.conversation_id); if (error) throw new Error(error.message); return { success: true }; });
route("setSilentPost", async (d) => { const x = body({ channelId: id, messageId: id, silent: z.boolean() }).parse(d); const c = await channel(x.channelId); await ca(x.clerkUserId, x.channelId); const { data, error } = await supabaseAdmin.from("messages").update({ silent: x.silent }).eq("id", x.messageId).eq("conversation_id", c.conversation_id).select().single(); if (error) throw new Error(error.message); return data; });
route("setAnonymousAdminPosting", async (d) => { const x = body({ channelId: id, enabled: z.boolean() }).parse(d); await ca(x.clerkUserId, x.channelId); const { data, error } = await supabaseAdmin.from("channels").update({ settings: { anonymousAdminPosting: x.enabled } }).eq("id", x.channelId).select().single(); if (error) throw new Error(error.message); return data; });
route("incrementPostView", async (d) => { const x = body({ channelId: id, messageId: id }).parse(d); await cm(x.clerkUserId, x.channelId); const { data, error } = await supabaseAdmin.rpc("increment_message_view_count", { p_message_id: x.messageId }); if (error) throw new Error(error.message); return { viewCount: data || 0 }; });
route("getPostViewCount", async (d) => { const x = body({ channelId: id, messageId: id }).parse(d); await cm(x.clerkUserId, x.channelId); const { data, error } = await supabaseAdmin.from("messages").select("view_count").eq("id", x.messageId).single(); if (error) throw new Error(error.message); return { viewCount: data.view_count || 0 }; });
route("linkCommentsGroup", async (d) => { const x = body({ channelId: id, groupId: id }).parse(d); await ca(x.clerkUserId, x.channelId); await ga(x.clerkUserId, x.groupId); const { error } = await supabaseAdmin.from("channel_comments_links").upsert({ channel_id: x.channelId, conversation_id: x.groupId }, { onConflict: "channel_id" }); if (error) throw new Error(error.message); return { success: true }; });
route("unlinkCommentsGroup", async (d) => { const x = body({ channelId: id }).parse(d); await ca(x.clerkUserId, x.channelId); const { error } = await supabaseAdmin.from("channel_comments_links").delete().eq("channel_id", x.channelId); if (error) throw new Error(error.message); return { success: true }; });
route("deleteAllMessagesFromUser", async (d) => { const x = body({ groupId: id, memberClerkId: str }).parse(d); await ga(x.clerkUserId, x.groupId); const { data: msgs } = await supabaseAdmin.from("messages").select("id").eq("conversation_id", x.groupId).eq("sender_clerk_id", x.memberClerkId); const ids = (msgs || []).map((m: any) => m.id); if (ids.length) { const { error } = await supabaseAdmin.from("messages").delete().in("id", ids); if (error) throw new Error(error.message); } return { success: true, deletedCount: ids.length }; });
route("pinMessage", async (d) => pin(d, true));
route("unpinMessage", async (d) => pin(d, false));
async function pin(d: any, pinned: boolean) { const x = body({ targetType: z.enum(["group", "channel"]), targetId: id, messageId: id }).parse(d); const c = x.targetType === "group" ? await group(x.targetId) : await channel(x.targetId); if (x.targetType === "group") await ga(x.clerkUserId, x.targetId); else await ca(x.clerkUserId, x.targetId); const { data, error } = await supabaseAdmin.from("messages").update({ pinned, pinned_at: pinned ? now() : null, pinned_by: pinned ? x.clerkUserId : null }).eq("id", x.messageId).eq("conversation_id", c.conversation_id || c.id).select().single(); if (error) throw new Error(error.message); emitPinUpdateEvent(x.targetId, { messageId: x.messageId, pinned }); return data; }
route("getPinnedMessages", async (d) => { const x = body({ targetType: z.enum(["group", "channel"]), targetId: id }).parse(d); const c = x.targetType === "group" ? await group(x.targetId) : await channel(x.targetId); if (x.targetType === "group") await gm(x.clerkUserId, x.targetId); else await cm(x.clerkUserId, x.targetId); const { data, error } = await supabaseAdmin.from("messages").select("*").eq("conversation_id", c.conversation_id || c.id).eq("pinned", true).order("pinned_at", { ascending: false }); if (error) throw new Error(error.message); return data || []; });

route("createInviteLink", async (d) => { const x = body({ targetType: z.enum(["group", "channel"]), targetId: id, expiresAt: z.string().datetime().nullable().optional(), maxUses: z.number().int().positive().nullable().optional() }).parse(d); if (x.targetType === "group") await ga(x.clerkUserId, x.targetId); else await ca(x.clerkUserId, x.targetId); const { data, error } = await supabaseAdmin.from("invite_links").insert({ target_type: x.targetType, target_id: x.targetId, token: token(), created_by: x.clerkUserId, expires_at: x.expiresAt || null, max_uses: x.maxUses || null }).select().single(); if (error) throw new Error(error.message); return data; });
route("revokeInviteLink", async (d) => { const x = body({ inviteId: id }).parse(d); const { data: invite } = await supabaseAdmin.from("invite_links").select("*").eq("id", x.inviteId).single(); if (!invite) throw new Error("Invite link not found"); if (invite.target_type === "group") await ga(x.clerkUserId, invite.target_id); else await ca(x.clerkUserId, invite.target_id); const { error } = await supabaseAdmin.from("invite_links").update({ revoked_at: now() }).eq("id", x.inviteId); if (error) throw new Error(error.message); return { success: true }; });
route("getInviteLinkInfo", async (d) => { const x = z.object({ clerkUserId: str, token: str }).parse(d); const { data, error } = await supabaseAdmin.from("invite_links").select("*").eq("token", x.token).is("revoked_at", null).maybeSingle(); if (error) throw new Error(error.message); if (!data) throw new Error("Invite link not found or revoked"); if (data.expires_at && new Date(data.expires_at) <= new Date()) throw new Error("Invite link expired"); return data; });
route("generateInviteQRCode", async (d) => { const x = body({ token: str }).parse(d); const { data } = await supabaseAdmin.from("invite_links").select("token").eq("token", x.token).is("revoked_at", null).maybeSingle(); if (!data) throw new Error("Invite link not found"); const value = `chatapp://invite/${data.token}`; return { value, qrCodeUrl: `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(value)}` }; });
route("setNotificationMute", async (d) => { const x = body({ targetType: z.enum(["group", "channel"]), targetId: id, muted: z.boolean() }).parse(d); if (x.targetType === "group") await gm(x.clerkUserId, x.targetId); else await cm(x.clerkUserId, x.targetId); const table = x.targetType === "group" ? "conversation_members" : "channel_members"; const key = x.targetType === "group" ? "conversation_id" : "channel_id"; const { error } = await supabaseAdmin.from(table).update(x.targetType === "group" ? { muted_until: x.muted ? new Date(Date.now() + 31536000000).toISOString() : null } : { muted: x.muted }).eq(key, x.targetId).eq("clerk_user_id", x.clerkUserId); if (error) throw new Error(error.message); return { success: true, muted: x.muted }; });
route("setMessageAutoDelete", async (d) => { const x = body({ groupId: id, seconds: z.number().int().min(0).max(7776000).nullable() }).parse(d); await ga(x.clerkUserId, x.groupId); const { error } = await supabaseAdmin.from("conversations").update({ auto_delete_seconds: x.seconds }).eq("id", x.groupId); if (error) throw new Error(error.message); return { success: true }; });
route("addAdmin", async (d) => roleAdmin(d, true));
route("removeAdmin", async (d) => roleAdmin(d, false));
async function roleAdmin(d: any, add: boolean) { const x = body({ targetType: z.enum(["group", "channel"]), targetId: id, memberClerkId: str }).parse(d); if (x.targetType === "group") await ga(x.clerkUserId, x.targetId); else await ca(x.clerkUserId, x.targetId); const table = x.targetType === "group" ? "conversation_members" : "channel_members"; const key = x.targetType === "group" ? "conversation_id" : "channel_id"; const { error } = await supabaseAdmin.from(table).update({ role: add ? "admin" : "member" }).eq(key, x.targetId).eq("clerk_user_id", x.memberClerkId); if (error) throw new Error(error.message); return { success: true, isAdmin: add }; }
route("setAdminPermissions", async (d) => { const x = body({ targetType: z.enum(["group", "channel"]), targetId: id, memberClerkId: str, permissions: z.record(z.boolean()) }).parse(d); if (x.targetType === "group") await ga(x.clerkUserId, x.targetId); else await ca(x.clerkUserId, x.targetId); const table = x.targetType === "group" ? "conversation_members" : "channel_members"; const key = x.targetType === "group" ? "conversation_id" : "channel_id"; const { error } = await supabaseAdmin.from(table).update({ permissions: x.permissions }).eq(key, x.targetId).eq("clerk_user_id", x.memberClerkId); if (error) throw new Error(error.message); return { success: true }; });
route("setAdminTitle", async (d) => { const x = body({ targetType: z.enum(["group", "channel"]), targetId: id, memberClerkId: str, title: z.string().max(100).nullable() }).parse(d); if (x.targetType === "group") await ga(x.clerkUserId, x.targetId); else await ca(x.clerkUserId, x.targetId); const table = x.targetType === "group" ? "conversation_members" : "channel_members"; const key = x.targetType === "group" ? "conversation_id" : "channel_id"; const { error } = await supabaseAdmin.from(table).update({ admin_title: x.title }).eq(key, x.targetId).eq("clerk_user_id", x.memberClerkId); if (error) throw new Error(error.message); return { success: true }; });
route("logAdminAction", async (d) => { const x = body({ targetType: z.enum(["group", "channel"]), targetId: id, action: str, targetClerkUserId: str.optional(), metadata: z.record(z.unknown()).default({}) }).parse(d); if (x.targetType === "group") await ga(x.clerkUserId, x.targetId); else await ca(x.clerkUserId, x.targetId); await audit(x.targetType, x.targetId, x.clerkUserId, x.action, x.targetClerkUserId, x.metadata); return { success: true }; });
route("getAdminAuditLog", async (d) => { const x = body({ targetType: z.enum(["group", "channel"]), targetId: id, limit: z.number().int().min(1).max(500).default(100) }).parse(d); if (x.targetType === "group") await ga(x.clerkUserId, x.targetId); else await ca(x.clerkUserId, x.targetId); const { data, error } = await supabaseAdmin.from("admin_audit_log").select("*").eq("target_type", x.targetType).eq("target_id", x.targetId).order("created_at", { ascending: false }).limit(x.limit); if (error) throw new Error(error.message); return data || []; });
route("searchPublicGroupsAndChannels", async (d) => { const x = body({ query: z.string().trim().min(1).max(100), limit: z.number().int().min(1).max(50).default(25) }).parse(d); const [{ data: groups }, { data: channels }] = await Promise.all([supabaseAdmin.from("conversations").select("id, name, description, type").eq("type", "group").ilike("name", `%${x.query}%`).is("deleted_at", null).limit(x.limit), supabaseAdmin.from("channels").select("id, name, description, public_slug, username, is_private").eq("is_private", false).eq("is_discoverable", true).ilike("name", `%${x.query}%`).is("archived_at", null).limit(x.limit)]); return { groups: groups || [], channels: channels || [] }; });

route("createJoinRequest", async (d) => { const x = body({ groupId: id, message: z.string().max(500).optional() }).parse(d); await group(x.groupId); const { data, error } = await supabaseAdmin.from("group_join_requests").upsert({ conversation_id: x.groupId, clerk_user_id: x.clerkUserId, message: x.message || null, status: "pending", reviewed_by: null, reviewed_at: null }, { onConflict: "conversation_id,clerk_user_id" }).select().single(); if (error) throw new Error(error.message); return data; });
route("approveJoinRequest", async (d) => reviewGroupJoin(d, "approved"));
route("rejectJoinRequest", async (d) => reviewGroupJoin(d, "rejected"));
async function reviewGroupJoin(d: any, status: string) { const x = body({ groupId: id, requestId: id }).parse(d); await ga(x.clerkUserId, x.groupId); const { data: request } = await supabaseAdmin.from("group_join_requests").select("*").eq("id", x.requestId).eq("conversation_id", x.groupId).single(); if (!request) throw new Error("Join request not found"); await supabaseAdmin.from("group_join_requests").update({ status, reviewed_by: x.clerkUserId, reviewed_at: now() }).eq("id", x.requestId); if (status === "approved") await supabaseAdmin.from("conversation_members").upsert({ conversation_id: x.groupId, clerk_user_id: request.clerk_user_id, role: "member" }, { onConflict: "conversation_id,clerk_user_id" }); return { success: true, status }; }

route("joinSocketRoom", async (d) => { const x = body({ room: z.string().min(1).max(200) }).parse(d); const socketIo = getIO(); if (!socketIo) throw new Error("Socket server unavailable"); return { success: true, room: x.room }; });
route("leaveSocketRoom", async (d) => { const x = body({ room: z.string().min(1).max(200) }).parse(d); return { success: true, room: x.room }; });
route("emitMembershipUpdate", async (d) => { const x = body({ room: str, payload: z.record(z.unknown()).default({}) }).parse(d); emitMembershipUpdate(x.room, x.payload); return { success: true }; });
route("emitRoleChangeEvent", async (d) => { const x = body({ room: str, payload: z.record(z.unknown()).default({}) }).parse(d); emitRoleChangeEvent(x.room, x.payload); return { success: true }; });
route("emitPinUpdateEvent", async (d) => { const x = body({ room: str, payload: z.record(z.unknown()).default({}) }).parse(d); emitPinUpdateEvent(x.room, x.payload); return { success: true }; });
route("emitNewPostEvent", async (d) => { const x = body({ room: str, payload: z.record(z.unknown()).default({}) }).parse(d); emitNewPostEvent(x.room, x.payload); return { success: true }; });
